cp node_modules/requirejs/require.js js/libs/node/require.js
cp node_modules/jquery/dist/jquery.min.js js/libs/node/jquery.min.js
cp node_modules/jqueryui/jquery-ui.min.js js/libs/node/jquery-ui.min.js
cp node_modules/jquery-hotkeys/jquery-hotkeys.js js/libs/node/jquery-hotkeys.js
cp node_modules/underscore/underscore-min.js js/libs/node/underscore-min.js
cp node_modules/backbone/backbone-min.js js/libs/node/backbone-min.js
cp node_modules/backbone/backbone-min.js.map js/libs/node/backbone-min.js.map
cp node_modules/handlebars/dist/handlebars.min.js js/libs/node/handlebars.min.js
cp node_modules/text/text.js js/libs/node/text.js